<MainScreen>:
    BoxLayout:
        orientation: 'vertical'
        Button:
            text: 'Operação'
            on_release: app.root.current = 'operacao'
        Button:
            text: 'Determinante'
            on_release: app.root.current = 'determinante'

<DeterminanteScreen>:
    BoxLayout:
        orientation: 'vertical'

<OperacaoScreen>:
    BoxLayout:
        orientation: 'vertical'

    
